#!/usr/local/ruby/bin/ruby
require "rubygems"
require "aws/s3"

if ARGV.size != 2
  puts "usage: upload_to_s3 file_path buck_name"
  exit
end

up_file, bucket = ARGV
unless File.exist?(up_file)
  puts "#{up_file} is no exist"
  exit
end

AWS::S3::Base.establish_connection!(
:access_key_id     => 'AKIAIRXV5QKMV54AINLA',
:secret_access_key => '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'
)

file_name = File.basename(up_file)
AWS::S3::S3Object.store(file_name, open(up_file), bucket)
puts "upload #{up_file} to #{bucket} success..."
